// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: record_alarm.proto

#ifndef PROTOBUF_record_5falarm_2eproto__INCLUDED
#define PROTOBUF_record_5falarm_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_record_5falarm_2eproto();
void protobuf_AssignDesc_record_5falarm_2eproto();
void protobuf_ShutdownFile_record_5falarm_2eproto();

class AlarmIndex;
class AlarmLevel;
class AlarmText;

// ===================================================================

class AlarmIndex : public ::google::protobuf::Message {
 public:
  AlarmIndex();
  virtual ~AlarmIndex();

  AlarmIndex(const AlarmIndex& from);

  inline AlarmIndex& operator=(const AlarmIndex& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AlarmIndex& default_instance();

  void Swap(AlarmIndex* other);

  // implements Message ----------------------------------------------

  AlarmIndex* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AlarmIndex& from);
  void MergeFrom(const AlarmIndex& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 alarm_index = 1;
  inline bool has_alarm_index() const;
  inline void clear_alarm_index();
  static const int kAlarmIndexFieldNumber = 1;
  inline ::google::protobuf::uint32 alarm_index() const;
  inline void set_alarm_index(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:AlarmIndex)
 private:
  inline void set_has_alarm_index();
  inline void clear_has_alarm_index();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 alarm_index_;
  friend void  protobuf_AddDesc_record_5falarm_2eproto();
  friend void protobuf_AssignDesc_record_5falarm_2eproto();
  friend void protobuf_ShutdownFile_record_5falarm_2eproto();

  void InitAsDefaultInstance();
  static AlarmIndex* default_instance_;
};
// -------------------------------------------------------------------

class AlarmLevel : public ::google::protobuf::Message {
 public:
  AlarmLevel();
  virtual ~AlarmLevel();

  AlarmLevel(const AlarmLevel& from);

  inline AlarmLevel& operator=(const AlarmLevel& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AlarmLevel& default_instance();

  void Swap(AlarmLevel* other);

  // implements Message ----------------------------------------------

  AlarmLevel* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AlarmLevel& from);
  void MergeFrom(const AlarmLevel& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 alarm_level = 1;
  inline bool has_alarm_level() const;
  inline void clear_alarm_level();
  static const int kAlarmLevelFieldNumber = 1;
  inline ::google::protobuf::uint32 alarm_level() const;
  inline void set_alarm_level(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:AlarmLevel)
 private:
  inline void set_has_alarm_level();
  inline void clear_has_alarm_level();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 alarm_level_;
  friend void  protobuf_AddDesc_record_5falarm_2eproto();
  friend void protobuf_AssignDesc_record_5falarm_2eproto();
  friend void protobuf_ShutdownFile_record_5falarm_2eproto();

  void InitAsDefaultInstance();
  static AlarmLevel* default_instance_;
};
// -------------------------------------------------------------------

class AlarmText : public ::google::protobuf::Message {
 public:
  AlarmText();
  virtual ~AlarmText();

  AlarmText(const AlarmText& from);

  inline AlarmText& operator=(const AlarmText& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AlarmText& default_instance();

  void Swap(AlarmText* other);

  // implements Message ----------------------------------------------

  AlarmText* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AlarmText& from);
  void MergeFrom(const AlarmText& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string alarm_text = 1;
  inline bool has_alarm_text() const;
  inline void clear_alarm_text();
  static const int kAlarmTextFieldNumber = 1;
  inline const ::std::string& alarm_text() const;
  inline void set_alarm_text(const ::std::string& value);
  inline void set_alarm_text(const char* value);
  inline void set_alarm_text(const char* value, size_t size);
  inline ::std::string* mutable_alarm_text();
  inline ::std::string* release_alarm_text();
  inline void set_allocated_alarm_text(::std::string* alarm_text);

  // optional uint32 log_module = 2;
  inline bool has_log_module() const;
  inline void clear_log_module();
  static const int kLogModuleFieldNumber = 2;
  inline ::google::protobuf::uint32 log_module() const;
  inline void set_log_module(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:AlarmText)
 private:
  inline void set_has_alarm_text();
  inline void clear_has_alarm_text();
  inline void set_has_log_module();
  inline void clear_has_log_module();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* alarm_text_;
  ::google::protobuf::uint32 log_module_;
  friend void  protobuf_AddDesc_record_5falarm_2eproto();
  friend void protobuf_AssignDesc_record_5falarm_2eproto();
  friend void protobuf_ShutdownFile_record_5falarm_2eproto();

  void InitAsDefaultInstance();
  static AlarmText* default_instance_;
};
// ===================================================================


// ===================================================================

// AlarmIndex

// required uint32 alarm_index = 1;
inline bool AlarmIndex::has_alarm_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AlarmIndex::set_has_alarm_index() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AlarmIndex::clear_has_alarm_index() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AlarmIndex::clear_alarm_index() {
  alarm_index_ = 0u;
  clear_has_alarm_index();
}
inline ::google::protobuf::uint32 AlarmIndex::alarm_index() const {
  // @@protoc_insertion_point(field_get:AlarmIndex.alarm_index)
  return alarm_index_;
}
inline void AlarmIndex::set_alarm_index(::google::protobuf::uint32 value) {
  set_has_alarm_index();
  alarm_index_ = value;
  // @@protoc_insertion_point(field_set:AlarmIndex.alarm_index)
}

// -------------------------------------------------------------------

// AlarmLevel

// required uint32 alarm_level = 1;
inline bool AlarmLevel::has_alarm_level() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AlarmLevel::set_has_alarm_level() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AlarmLevel::clear_has_alarm_level() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AlarmLevel::clear_alarm_level() {
  alarm_level_ = 0u;
  clear_has_alarm_level();
}
inline ::google::protobuf::uint32 AlarmLevel::alarm_level() const {
  // @@protoc_insertion_point(field_get:AlarmLevel.alarm_level)
  return alarm_level_;
}
inline void AlarmLevel::set_alarm_level(::google::protobuf::uint32 value) {
  set_has_alarm_level();
  alarm_level_ = value;
  // @@protoc_insertion_point(field_set:AlarmLevel.alarm_level)
}

// -------------------------------------------------------------------

// AlarmText

// required string alarm_text = 1;
inline bool AlarmText::has_alarm_text() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AlarmText::set_has_alarm_text() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AlarmText::clear_has_alarm_text() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AlarmText::clear_alarm_text() {
  if (alarm_text_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    alarm_text_->clear();
  }
  clear_has_alarm_text();
}
inline const ::std::string& AlarmText::alarm_text() const {
  // @@protoc_insertion_point(field_get:AlarmText.alarm_text)
  return *alarm_text_;
}
inline void AlarmText::set_alarm_text(const ::std::string& value) {
  set_has_alarm_text();
  if (alarm_text_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    alarm_text_ = new ::std::string;
  }
  alarm_text_->assign(value);
  // @@protoc_insertion_point(field_set:AlarmText.alarm_text)
}
inline void AlarmText::set_alarm_text(const char* value) {
  set_has_alarm_text();
  if (alarm_text_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    alarm_text_ = new ::std::string;
  }
  alarm_text_->assign(value);
  // @@protoc_insertion_point(field_set_char:AlarmText.alarm_text)
}
inline void AlarmText::set_alarm_text(const char* value, size_t size) {
  set_has_alarm_text();
  if (alarm_text_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    alarm_text_ = new ::std::string;
  }
  alarm_text_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:AlarmText.alarm_text)
}
inline ::std::string* AlarmText::mutable_alarm_text() {
  set_has_alarm_text();
  if (alarm_text_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    alarm_text_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:AlarmText.alarm_text)
  return alarm_text_;
}
inline ::std::string* AlarmText::release_alarm_text() {
  clear_has_alarm_text();
  if (alarm_text_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = alarm_text_;
    alarm_text_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void AlarmText::set_allocated_alarm_text(::std::string* alarm_text) {
  if (alarm_text_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete alarm_text_;
  }
  if (alarm_text) {
    set_has_alarm_text();
    alarm_text_ = alarm_text;
  } else {
    clear_has_alarm_text();
    alarm_text_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:AlarmText.alarm_text)
}

// optional uint32 log_module = 2;
inline bool AlarmText::has_log_module() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AlarmText::set_has_log_module() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AlarmText::clear_has_log_module() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AlarmText::clear_log_module() {
  log_module_ = 0u;
  clear_has_log_module();
}
inline ::google::protobuf::uint32 AlarmText::log_module() const {
  // @@protoc_insertion_point(field_get:AlarmText.log_module)
  return log_module_;
}
inline void AlarmText::set_log_module(::google::protobuf::uint32 value) {
  set_has_log_module();
  log_module_ = value;
  // @@protoc_insertion_point(field_set:AlarmText.log_module)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_record_5falarm_2eproto__INCLUDED
