#ifndef __RECORD_GROUP_CDB_H__
#define __RECORD_GROUP_CDB_H__

/* This file defines all the record IDs within RECORD_GROUP_CDB and db column IDs.
 * Define request and response message ID in a pair. i.e.  <n, n+1>
 * Naming convention: CDB_WORD1_..._WORDn, multiple WORDs are alllowed
 * after the group name CDB_
 */

#include "vnf_limits.h"
#include "record_group.h"

#include "record_cdb_id_cm.h" 
//#include "record_cdb_id_xxx.h

#undef DEFINE_ENUM
// adding prefix to avoid conflict
#define DEFINE_ENUM(name) CDB_##name

typedef enum {
    DEFINE_ENUM(VNF_HA),
    DEFINE_ENUM(VNF_HA_MONITOR_TARGET),
    DEFINE_ENUM(VNF_HA_MONITOR_MEMBER),
    DEFINE_ENUM(VNF_HA_MONITOR_GROUP),
    DEFINE_ENUM(VNF_HA_MONITOR_MEMBER_GROUP),
    DEFINE_ENUM(WAG_RADIUS_INTF),
    DEFINE_ENUM(WAG_RADIUS_INTF_ORIG_IF),
    DEFINE_ENUM(WAG_RADIUS_INTF_PEER),
    DEFINE_ENUM(WIFISSID),
    DEFINE_ENUM(WIFISSID_EP),
    DEFINE_ENUM(WIFI_AUTHOR_PROFILE),
    DEFINE_ENUM(WIFI_AUTHEN_PROFILE),
    DEFINE_ENUM(WIFI_ACCT_PROFILE),
    DEFINE_ENUM(WIFI_KEY_ID_MAP),
    DEFINE_ENUM(WIFI_GLOBAL_KEY_ID_MAP),
    DEFINE_ENUM(CGNAT_INIT_QAM_IP_QUOTA),
    DEFINE_ENUM(CGNAT_GLOBAL_CONFIG),
    DEFINE_ENUM(CGNAT_PROFILE_KEY),
    DEFINE_ENUM(CGNAT_IP_POOL_KEY),
    DEFINE_ENUM(CGNAT_TCP_SESSION_TIMEOUT),
    DEFINE_ENUM(CGNAT_TYPE_INT),
    DEFINE_ENUM(TEST_ARRAY),
    DEFINE_ENUM(TEST_BASIC), 
    DEFINE_ENUM(CGNAT_IP_V4_RANGE),
    DEFINE_ENUM(CGNAT_IP_V6_RANGE),
    DEFINE_ENUM(CGNAT_IP_POOL_DATA_POOL),
    DEFINE_ENUM(CGNAT_IP_POOL_DATA_RUNNING),
    DEFINE_ENUM(CGNAT_IP_POOL_DATA_PROFILE),
    DEFINE_ENUM(CGNAT_IP_POOL_DATA),
    DEFINE_ENUM(CGNAT_PROFILE),
    DEFINE_ENUM(CGNAT_GLOBAL),    
    DEFINE_ENUM(CGNAT_GLOBAL_PROFILE),    
    DEFINE_ENUM(CGNAT_GLOBAL_IP_POOL),    
    DEFINE_ENUM(CGNAT_SYSLOG_SERVER),    
    DEFINE_ENUM(CGNAT_SYSLOG_SERVERS),    
    DEFINE_ENUM(CGNAT_TEST),    
    DEFINE_ENUM(CGNAT_PROFILE_DATA),
    DEFINE_ENUM(CGNAT_PROFILE_DATA_BASIC),
    DEFINE_ENUM(CGNAT_PROFILE_DATA_SSID),
    DEFINE_ENUM(WIFI_SUBNET),
    DEFINE_ENUM(WIFI_LOGIC_INTF),
    DEFINE_ENUM(DHCPMGR_GLOBAL_CONFIG),
    DEFINE_ENUM(WIFI_SVCPOLICY),
    DEFINE_ENUM(WIFI_SVCPOLICY_RULE),
    DEFINE_ENUM(WIFISVC_GLOBAL_CONFIG),
    DEFINE_ENUM(WIFIDBG_GLOBAL_CONFIG),
    DEFINE_ENUM(WIFI_KEY_ID_MAP_SSID_NAME),
    DEFINE_ENUM(WIFI_KEY_ID_MAP_SSID_ID),
    DEFINE_ENUM(WIFI_KEY_ID_MAP_INTF_NAME),
    DEFINE_ENUM(WIFI_KEY_ID_MAP_INTF_ID),
    DEFINE_ENUM(WIFI_BIND_RECORD),
#define XX(tag) DEFINE_ENUM(tag), 
    CDB_ID_CM_RECORDS
#undef XX
//  CDB_ID_XXX_RECORDS
// Find all CDB_ID_XXX record definitions above 

    DEFINE_ENUM(LAST_ONE)
}RECORDCdb;

#if DEFINE_ENUM(LAST_ONE) > RECORD_PER_GROUP
#error "Exceeding max number of messages per group, create a new group to continue"
#endif

#endif
