/*************************************************************************
 Casa Systems Inc.
 Copyright (C) 2015
 All Rights Reserved.

 This file contains proprietary trade secrets of Casa Systems, Inc. No part
 of this file may be reproduced or transmitted in any form or by any means,
 electronic or mechanical, including photocopying and recording, for any
 purpose without the expressed written permission of Casa Systems, Inc.

 File: record_common.h

 Author: Lian Li
 Date:   Dec. 2, 2015

 Header file for common data structures used by messaging service.

 Revision History:
*************************************************************************/
#ifndef __RECORD_COMMON_H__
#define __RECORD_COMMON_H__

#include <stdint.h>
#include "vnf_limits.h"
#include "record_ha.h"

#define MROUTER_PORT 9090
/* 256 = 2^8 */
#define RECORD_TYPE_BITS 16
#if RECORD_PER_GROUP != 65536
#error "Mismatch with vnf_limits.h"
#endif

typedef uint32_t RecordID;

#define RECORDID(group, type) ((RecordID)(((RECORD_GROUP_##group)<<RECORD_TYPE_BITS) | (group##_##type)))
#define NULL_RECORDID ((RecordID)(0))

/* This macro abstracts the init function generated by protocol-buffer-c */
#define RECORD_INIT(group, type) group##_##type##__INIT

#endif
