
/************************************************
 * Generated by record_table_gen.py. DO NOT modify *
 ************************************************
 */
#include "record_table.h"
#include "record_ha.h"
#include "record_cdb.h"
#include "record_alarm.h"
#include "record_alarm.pb-c.h"
#include "record_cdb.pb-c.h"
#include "record_ha.pb-c.h"

RecordMetaInfo record_meta_table[RECORD_GROUP_MAXNUM * RECORD_PER_GROUP];
static int table_initialized = 0;

RecordMetaInfo *lookup_record_meta_table(uint32_t record_id)
{
    if ( record_id >= RECORD_GROUP_MAXNUM*RECORD_PER_GROUP ) return NULL;
    return  &record_meta_table[ record_id ];

}

#define SET_META_INFO( entry, name_str, f1, f2, f3, f4 ) \
        (entry)->name            = (char *)name_str; \
        (entry)->get_packed_size = (GET_PACKED_SIZE_FUNC)f1; \
        (entry)->pack            = (PACK_FUNC)f2; \
        (entry)->unpack          = (UNPACK_FUNC)f3; \
        (entry)->free_unpacked   = (FREE_UNPACKED_FUNC)f4;

void record_meta_table_init()
{
    if ( table_initialized ) return;
    table_initialized = 1;

    RecordMetaInfo *entry;
    entry = &record_meta_table[RECORDID(ALARM,INDEX)];
    SET_META_INFO(entry,
                  "AlarmIndex",
                  alarm_index__get_packed_size,
                  alarm_index__pack,
                  alarm_index__unpack,
                  alarm_index__free_unpacked);
    entry = &record_meta_table[RECORDID(ALARM,LEVEL)];
    SET_META_INFO(entry,
                  "AlarmLevel",
                  alarm_level__get_packed_size,
                  alarm_level__pack,
                  alarm_level__unpack,
                  alarm_level__free_unpacked);
    entry = &record_meta_table[RECORDID(ALARM,TEXT)];
    SET_META_INFO(entry,
                  "AlarmText",
                  alarm_text__get_packed_size,
                  alarm_text__pack,
                  alarm_text__unpack,
                  alarm_text__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,VNF_HA_MONITOR_TARGET)];
    SET_META_INFO(entry,
                  "CdbVnfHaMonitorTarget",
                  cdb_vnf_ha_monitor_target__get_packed_size,
                  cdb_vnf_ha_monitor_target__pack,
                  cdb_vnf_ha_monitor_target__unpack,
                  cdb_vnf_ha_monitor_target__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,VNF_HA_MONITOR_MEMBER)];
    SET_META_INFO(entry,
                  "CdbVnfHaMonitorMember",
                  cdb_vnf_ha_monitor_member__get_packed_size,
                  cdb_vnf_ha_monitor_member__pack,
                  cdb_vnf_ha_monitor_member__unpack,
                  cdb_vnf_ha_monitor_member__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,VNF_HA_MONITOR_GROUP)];
    SET_META_INFO(entry,
                  "CdbVnfHaMonitorGroup",
                  cdb_vnf_ha_monitor_group__get_packed_size,
                  cdb_vnf_ha_monitor_group__pack,
                  cdb_vnf_ha_monitor_group__unpack,
                  cdb_vnf_ha_monitor_group__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,VNF_HA_MONITOR_MEMBER_GROUP)];
    SET_META_INFO(entry,
                  "CdbVnfHaMonitorMemberGroup",
                  cdb_vnf_ha_monitor_member_group__get_packed_size,
                  cdb_vnf_ha_monitor_member_group__pack,
                  cdb_vnf_ha_monitor_member_group__unpack,
                  cdb_vnf_ha_monitor_member_group__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,VNF_HA)];
    SET_META_INFO(entry,
                  "CdbVnfHa",
                  cdb_vnf_ha__get_packed_size,
                  cdb_vnf_ha__pack,
                  cdb_vnf_ha__unpack,
                  cdb_vnf_ha__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WAG_RADIUS_INTF_ORIG_IF)];
    SET_META_INFO(entry,
                  "CdbWagRadiusIntfOrigIf",
                  cdb_wag_radius_intf_orig_if__get_packed_size,
                  cdb_wag_radius_intf_orig_if__pack,
                  cdb_wag_radius_intf_orig_if__unpack,
                  cdb_wag_radius_intf_orig_if__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WAG_RADIUS_INTF_PEER)];
    SET_META_INFO(entry,
                  "CdbWagRadiusIntfPeer",
                  cdb_wag_radius_intf_peer__get_packed_size,
                  cdb_wag_radius_intf_peer__pack,
                  cdb_wag_radius_intf_peer__unpack,
                  cdb_wag_radius_intf_peer__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WAG_RADIUS_INTF)];
    SET_META_INFO(entry,
                  "CdbWagRadiusIntf",
                  cdb_wag_radius_intf__get_packed_size,
                  cdb_wag_radius_intf__pack,
                  cdb_wag_radius_intf__unpack,
                  cdb_wag_radius_intf__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFISSID_EP)];
    SET_META_INFO(entry,
                  "CdbWifissidEp",
                  cdb_wifissid_ep__get_packed_size,
                  cdb_wifissid_ep__pack,
                  cdb_wifissid_ep__unpack,
                  cdb_wifissid_ep__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFISSID)];
    SET_META_INFO(entry,
                  "CdbWifissid",
                  cdb_wifissid__get_packed_size,
                  cdb_wifissid__pack,
                  cdb_wifissid__unpack,
                  cdb_wifissid__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFI_AUTHOR_PROFILE)];
    SET_META_INFO(entry,
                  "CdbWifiAuthorProfile",
                  cdb_wifi_author_profile__get_packed_size,
                  cdb_wifi_author_profile__pack,
                  cdb_wifi_author_profile__unpack,
                  cdb_wifi_author_profile__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFI_AUTHEN_PROFILE)];
    SET_META_INFO(entry,
                  "CdbWifiAuthenProfile",
                  cdb_wifi_authen_profile__get_packed_size,
                  cdb_wifi_authen_profile__pack,
                  cdb_wifi_authen_profile__unpack,
                  cdb_wifi_authen_profile__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFI_ACCT_PROFILE)];
    SET_META_INFO(entry,
                  "CdbWifiAcctProfile",
                  cdb_wifi_acct_profile__get_packed_size,
                  cdb_wifi_acct_profile__pack,
                  cdb_wifi_acct_profile__unpack,
                  cdb_wifi_acct_profile__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFI_KEY_ID_MAP)];
    SET_META_INFO(entry,
                  "CdbWifiKeyIdMap",
                  cdb_wifi_key_id_map__get_packed_size,
                  cdb_wifi_key_id_map__pack,
                  cdb_wifi_key_id_map__unpack,
                  cdb_wifi_key_id_map__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFI_GLOBAL_KEY_ID_MAP)];
    SET_META_INFO(entry,
                  "CdbWifiGlobalKeyIdMap",
                  cdb_wifi_global_key_id_map__get_packed_size,
                  cdb_wifi_global_key_id_map__pack,
                  cdb_wifi_global_key_id_map__unpack,
                  cdb_wifi_global_key_id_map__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFI_KEY_ID_MAP_SSID_NAME)];
    SET_META_INFO(entry,
                  "CdbWifiKeyIdMapSsidName",
                  cdb_wifi_key_id_map_ssid_name__get_packed_size,
                  cdb_wifi_key_id_map_ssid_name__pack,
                  cdb_wifi_key_id_map_ssid_name__unpack,
                  cdb_wifi_key_id_map_ssid_name__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFI_KEY_ID_MAP_SSID_ID)];
    SET_META_INFO(entry,
                  "CdbWifiKeyIdMapSsidId",
                  cdb_wifi_key_id_map_ssid_id__get_packed_size,
                  cdb_wifi_key_id_map_ssid_id__pack,
                  cdb_wifi_key_id_map_ssid_id__unpack,
                  cdb_wifi_key_id_map_ssid_id__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFI_KEY_ID_MAP_INTF_NAME)];
    SET_META_INFO(entry,
                  "CdbWifiKeyIdMapIntfName",
                  cdb_wifi_key_id_map_intf_name__get_packed_size,
                  cdb_wifi_key_id_map_intf_name__pack,
                  cdb_wifi_key_id_map_intf_name__unpack,
                  cdb_wifi_key_id_map_intf_name__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFI_KEY_ID_MAP_INTF_ID)];
    SET_META_INFO(entry,
                  "CdbWifiKeyIdMapIntfId",
                  cdb_wifi_key_id_map_intf_id__get_packed_size,
                  cdb_wifi_key_id_map_intf_id__pack,
                  cdb_wifi_key_id_map_intf_id__unpack,
                  cdb_wifi_key_id_map_intf_id__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_INIT_QAM_IP_QUOTA)];
    SET_META_INFO(entry,
                  "CdbCgnatInitQamIpQuota",
                  cdb_cgnat_init_qam_ip_quota__get_packed_size,
                  cdb_cgnat_init_qam_ip_quota__pack,
                  cdb_cgnat_init_qam_ip_quota__unpack,
                  cdb_cgnat_init_qam_ip_quota__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_PROFILE_KEY)];
    SET_META_INFO(entry,
                  "CdbCgnatProfileKey",
                  cdb_cgnat_profile_key__get_packed_size,
                  cdb_cgnat_profile_key__pack,
                  cdb_cgnat_profile_key__unpack,
                  cdb_cgnat_profile_key__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_IP_POOL_KEY)];
    SET_META_INFO(entry,
                  "CdbCgnatIpPoolKey",
                  cdb_cgnat_ip_pool_key__get_packed_size,
                  cdb_cgnat_ip_pool_key__pack,
                  cdb_cgnat_ip_pool_key__unpack,
                  cdb_cgnat_ip_pool_key__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_GLOBAL_CONFIG)];
    SET_META_INFO(entry,
                  "CdbCgnatGlobalConfig",
                  cdb_cgnat_global_config__get_packed_size,
                  cdb_cgnat_global_config__pack,
                  cdb_cgnat_global_config__unpack,
                  cdb_cgnat_global_config__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_TYPE_INT)];
    SET_META_INFO(entry,
                  "CdbCgnatTypeInt",
                  cdb_cgnat_type_int__get_packed_size,
                  cdb_cgnat_type_int__pack,
                  cdb_cgnat_type_int__unpack,
                  cdb_cgnat_type_int__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_GLOBAL_PROFILE)];
    SET_META_INFO(entry,
                  "CdbCgnatGlobalProfile",
                  cdb_cgnat_global_profile__get_packed_size,
                  cdb_cgnat_global_profile__pack,
                  cdb_cgnat_global_profile__unpack,
                  cdb_cgnat_global_profile__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_GLOBAL_IP_POOL)];
    SET_META_INFO(entry,
                  "CdbCgnatGlobalIpPool",
                  cdb_cgnat_global_ip_pool__get_packed_size,
                  cdb_cgnat_global_ip_pool__pack,
                  cdb_cgnat_global_ip_pool__unpack,
                  cdb_cgnat_global_ip_pool__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_SYSLOG_SERVER)];
    SET_META_INFO(entry,
                  "CdbCgnatSyslogServer",
                  cdb_cgnat_syslog_server__get_packed_size,
                  cdb_cgnat_syslog_server__pack,
                  cdb_cgnat_syslog_server__unpack,
                  cdb_cgnat_syslog_server__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_SYSLOG_SERVERS)];
    SET_META_INFO(entry,
                  "CdbCgnatSyslogServers",
                  cdb_cgnat_syslog_servers__get_packed_size,
                  cdb_cgnat_syslog_servers__pack,
                  cdb_cgnat_syslog_servers__unpack,
                  cdb_cgnat_syslog_servers__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_GLOBAL)];
    SET_META_INFO(entry,
                  "CdbCgnatGlobal",
                  cdb_cgnat_global__get_packed_size,
                  cdb_cgnat_global__pack,
                  cdb_cgnat_global__unpack,
                  cdb_cgnat_global__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,TEST_ARRAY)];
    SET_META_INFO(entry,
                  "CdbTestArray",
                  cdb_test_array__get_packed_size,
                  cdb_test_array__pack,
                  cdb_test_array__unpack,
                  cdb_test_array__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,TEST_BASIC)];
    SET_META_INFO(entry,
                  "CdbTestBasic",
                  cdb_test_basic__get_packed_size,
                  cdb_test_basic__pack,
                  cdb_test_basic__unpack,
                  cdb_test_basic__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_TEST)];
    SET_META_INFO(entry,
                  "CdbCgnatTest",
                  cdb_cgnat_test__get_packed_size,
                  cdb_cgnat_test__pack,
                  cdb_cgnat_test__unpack,
                  cdb_cgnat_test__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_TCP_SESSION_TIMEOUT)];
    SET_META_INFO(entry,
                  "CdbCgnatTcpSessionTimeout",
                  cdb_cgnat_tcp_session_timeout__get_packed_size,
                  cdb_cgnat_tcp_session_timeout__pack,
                  cdb_cgnat_tcp_session_timeout__unpack,
                  cdb_cgnat_tcp_session_timeout__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_PROFILE_DATA_SSID)];
    SET_META_INFO(entry,
                  "CdbCgnatProfileDataSsid",
                  cdb_cgnat_profile_data_ssid__get_packed_size,
                  cdb_cgnat_profile_data_ssid__pack,
                  cdb_cgnat_profile_data_ssid__unpack,
                  cdb_cgnat_profile_data_ssid__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_PROFILE_DATA_BASIC)];
    SET_META_INFO(entry,
                  "CdbCgnatProfileDataBasic",
                  cdb_cgnat_profile_data_basic__get_packed_size,
                  cdb_cgnat_profile_data_basic__pack,
                  cdb_cgnat_profile_data_basic__unpack,
                  cdb_cgnat_profile_data_basic__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_PROFILE_DATA)];
    SET_META_INFO(entry,
                  "CdbCgnatProfileData",
                  cdb_cgnat_profile_data__get_packed_size,
                  cdb_cgnat_profile_data__pack,
                  cdb_cgnat_profile_data__unpack,
                  cdb_cgnat_profile_data__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_IP_V4_RANGE)];
    SET_META_INFO(entry,
                  "CdbCgnatIpV4Range",
                  cdb_cgnat_ip_v4_range__get_packed_size,
                  cdb_cgnat_ip_v4_range__pack,
                  cdb_cgnat_ip_v4_range__unpack,
                  cdb_cgnat_ip_v4_range__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_IP_V6_RANGE)];
    SET_META_INFO(entry,
                  "CdbCgnatIpV6Range",
                  cdb_cgnat_ip_v6_range__get_packed_size,
                  cdb_cgnat_ip_v6_range__pack,
                  cdb_cgnat_ip_v6_range__unpack,
                  cdb_cgnat_ip_v6_range__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_IP_POOL_DATA_POOL)];
    SET_META_INFO(entry,
                  "CdbCgnatIpPoolDataPool",
                  cdb_cgnat_ip_pool_data_pool__get_packed_size,
                  cdb_cgnat_ip_pool_data_pool__pack,
                  cdb_cgnat_ip_pool_data_pool__unpack,
                  cdb_cgnat_ip_pool_data_pool__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_IP_POOL_DATA_RUNNING)];
    SET_META_INFO(entry,
                  "CdbCgnatIpPoolDataRunning",
                  cdb_cgnat_ip_pool_data_running__get_packed_size,
                  cdb_cgnat_ip_pool_data_running__pack,
                  cdb_cgnat_ip_pool_data_running__unpack,
                  cdb_cgnat_ip_pool_data_running__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_IP_POOL_DATA_PROFILE)];
    SET_META_INFO(entry,
                  "CdbCgnatIpPoolDataProfile",
                  cdb_cgnat_ip_pool_data_profile__get_packed_size,
                  cdb_cgnat_ip_pool_data_profile__pack,
                  cdb_cgnat_ip_pool_data_profile__unpack,
                  cdb_cgnat_ip_pool_data_profile__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,CGNAT_IP_POOL_DATA)];
    SET_META_INFO(entry,
                  "CdbCgnatIpPoolData",
                  cdb_cgnat_ip_pool_data__get_packed_size,
                  cdb_cgnat_ip_pool_data__pack,
                  cdb_cgnat_ip_pool_data__unpack,
                  cdb_cgnat_ip_pool_data__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFI_SUBNET)];
    SET_META_INFO(entry,
                  "CdbWifiSubnet",
                  cdb_wifi_subnet__get_packed_size,
                  cdb_wifi_subnet__pack,
                  cdb_wifi_subnet__unpack,
                  cdb_wifi_subnet__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFI_LOGIC_INTF)];
    SET_META_INFO(entry,
                  "CdbWifiLogicIntf",
                  cdb_wifi_logic_intf__get_packed_size,
                  cdb_wifi_logic_intf__pack,
                  cdb_wifi_logic_intf__unpack,
                  cdb_wifi_logic_intf__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,DHCPMGR_GLOBAL_CONFIG)];
    SET_META_INFO(entry,
                  "CdbDhcpmgrGlobalConfig",
                  cdb_dhcpmgr_global_config__get_packed_size,
                  cdb_dhcpmgr_global_config__pack,
                  cdb_dhcpmgr_global_config__unpack,
                  cdb_dhcpmgr_global_config__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFI_SVCPOLICY_RULE)];
    SET_META_INFO(entry,
                  "CdbWifiSvcpolicyRule",
                  cdb_wifi_svcpolicy_rule__get_packed_size,
                  cdb_wifi_svcpolicy_rule__pack,
                  cdb_wifi_svcpolicy_rule__unpack,
                  cdb_wifi_svcpolicy_rule__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFI_SVCPOLICY)];
    SET_META_INFO(entry,
                  "CdbWifiSvcpolicy",
                  cdb_wifi_svcpolicy__get_packed_size,
                  cdb_wifi_svcpolicy__pack,
                  cdb_wifi_svcpolicy__unpack,
                  cdb_wifi_svcpolicy__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFISVC_GLOBAL_CONFIG)];
    SET_META_INFO(entry,
                  "CdbWifisvcGlobalConfig",
                  cdb_wifisvc_global_config__get_packed_size,
                  cdb_wifisvc_global_config__pack,
                  cdb_wifisvc_global_config__unpack,
                  cdb_wifisvc_global_config__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFI_BIND_RECORD)];
    SET_META_INFO(entry,
                  "CdbWifiBindRecord",
                  cdb_wifi_bind_record__get_packed_size,
                  cdb_wifi_bind_record__pack,
                  cdb_wifi_bind_record__unpack,
                  cdb_wifi_bind_record__free_unpacked);
    entry = &record_meta_table[RECORDID(CDB,WIFIDBG_GLOBAL_CONFIG)];
    SET_META_INFO(entry,
                  "CdbWifidbgGlobalConfig",
                  cdb_wifidbg_global_config__get_packed_size,
                  cdb_wifidbg_global_config__pack,
                  cdb_wifidbg_global_config__unpack,
                  cdb_wifidbg_global_config__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,IPSEC_START_TIME)];
    SET_META_INFO(entry,
                  "HaIpsecStartTime",
                  ha_ipsec_start_time__get_packed_size,
                  ha_ipsec_start_time__pack,
                  ha_ipsec_start_time__unpack,
                  ha_ipsec_start_time__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,IKE_PEER)];
    SET_META_INFO(entry,
                  "HaIkePeer",
                  ha_ike_peer__get_packed_size,
                  ha_ike_peer__pack,
                  ha_ike_peer__unpack,
                  ha_ike_peer__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,IKE_INFO)];
    SET_META_INFO(entry,
                  "HaIkeInfo",
                  ha_ike_info__get_packed_size,
                  ha_ike_info__pack,
                  ha_ike_info__unpack,
                  ha_ike_info__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,IKE_EPDG_CTX)];
    SET_META_INFO(entry,
                  "HaIkeEpdgCtx",
                  ha_ike_epdg_ctx__get_packed_size,
                  ha_ike_epdg_ctx__pack,
                  ha_ike_epdg_ctx__unpack,
                  ha_ike_epdg_ctx__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,IKE_STAT)];
    SET_META_INFO(entry,
                  "HaIkeStat",
                  ha_ike_stat__get_packed_size,
                  ha_ike_stat__pack,
                  ha_ike_stat__unpack,
                  ha_ike_stat__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,CHILD_INFO)];
    SET_META_INFO(entry,
                  "HaChildInfo",
                  ha_child_info__get_packed_size,
                  ha_child_info__pack,
                  ha_child_info__unpack,
                  ha_child_info__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,CHILD_KEY_EX)];
    SET_META_INFO(entry,
                  "HaChildKeyEx",
                  ha_child_key_ex__get_packed_size,
                  ha_child_key_ex__pack,
                  ha_child_key_ex__unpack,
                  ha_child_key_ex__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,CHILD_STAT)];
    SET_META_INFO(entry,
                  "HaChildStat",
                  ha_child_stat__get_packed_size,
                  ha_child_stat__pack,
                  ha_child_stat__unpack,
                  ha_child_stat__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,SWM_DIAM)];
    SET_META_INFO(entry,
                  "HaSwmDiam",
                  ha_swm_diam__get_packed_size,
                  ha_swm_diam__pack,
                  ha_swm_diam__unpack,
                  ha_swm_diam__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,IPPOOL)];
    SET_META_INFO(entry,
                  "HaIppool",
                  ha_ippool__get_packed_size,
                  ha_ippool__pack,
                  ha_ippool__unpack,
                  ha_ippool__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,EPDG_SESSION_COMMON)];
    SET_META_INFO(entry,
                  "HaEpdgSessionCommon",
                  ha_epdg_session_common__get_packed_size,
                  ha_epdg_session_common__pack,
                  ha_epdg_session_common__unpack,
                  ha_epdg_session_common__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,EPDG_SESSION_UE)];
    SET_META_INFO(entry,
                  "HaEpdgSessionUe",
                  ha_epdg_session_ue__get_packed_size,
                  ha_epdg_session_ue__pack,
                  ha_epdg_session_ue__unpack,
                  ha_epdg_session_ue__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,EPDG_SESSION_APN_AMBR)];
    SET_META_INFO(entry,
                  "HaEpdgSessionApnAmbr",
                  ha_epdg_session_apn_ambr__get_packed_size,
                  ha_epdg_session_apn_ambr__pack,
                  ha_epdg_session_apn_ambr__unpack,
                  ha_epdg_session_apn_ambr__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,EPDG_BEARER_COMMON)];
    SET_META_INFO(entry,
                  "HaEpdgBearerCommon",
                  ha_epdg_bearer_common__get_packed_size,
                  ha_epdg_bearer_common__pack,
                  ha_epdg_bearer_common__unpack,
                  ha_epdg_bearer_common__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,EPDG_BEARER_QOS)];
    SET_META_INFO(entry,
                  "HaEpdgBearerQos",
                  ha_epdg_bearer_qos__get_packed_size,
                  ha_epdg_bearer_qos__pack,
                  ha_epdg_bearer_qos__unpack,
                  ha_epdg_bearer_qos__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,S1MME_INST_CFG)];
    SET_META_INFO(entry,
                  "HaS1mmeInstCfg",
                  ha_s1mme_inst_cfg__get_packed_size,
                  ha_s1mme_inst_cfg__pack,
                  ha_s1mme_inst_cfg__unpack,
                  ha_s1mme_inst_cfg__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,S1MME_LENB)];
    SET_META_INFO(entry,
                  "HaS1mmeLenb",
                  ha_s1mme_lenb__get_packed_size,
                  ha_s1mme_lenb__pack,
                  ha_s1mme_lenb__unpack,
                  ha_s1mme_lenb__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,S1MME_MME_CB)];
    SET_META_INFO(entry,
                  "HaS1mmeMmeCb",
                  ha_s1mme_mme_cb__get_packed_size,
                  ha_s1mme_mme_cb__pack,
                  ha_s1mme_mme_cb__unpack,
                  ha_s1mme_mme_cb__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,S1MME_MME_PLMN)];
    SET_META_INFO(entry,
                  "HaS1mmeMmePlmn",
                  ha_s1mme_mme_plmn__get_packed_size,
                  ha_s1mme_mme_plmn__pack,
                  ha_s1mme_mme_plmn__unpack,
                  ha_s1mme_mme_plmn__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,S1MME_MME_MMECS)];
    SET_META_INFO(entry,
                  "HaS1mmeMmeMmecs",
                  ha_s1mme_mme_mmecs__get_packed_size,
                  ha_s1mme_mme_mmecs__pack,
                  ha_s1mme_mme_mmecs__unpack,
                  ha_s1mme_mme_mmecs__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,S1MME_MME_GROUPID)];
    SET_META_INFO(entry,
                  "HaS1mmeMmeGroupid",
                  ha_s1mme_mme_groupid__get_packed_size,
                  ha_s1mme_mme_groupid__pack,
                  ha_s1mme_mme_groupid__unpack,
                  ha_s1mme_mme_groupid__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,S1MME_SUPTD_TAI)];
    SET_META_INFO(entry,
                  "HaS1mmeSuptdTai",
                  ha_s1mme_suptd_tai__get_packed_size,
                  ha_s1mme_suptd_tai__pack,
                  ha_s1mme_suptd_tai__unpack,
                  ha_s1mme_suptd_tai__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,S1MME_HENB_CB)];
    SET_META_INFO(entry,
                  "HaS1mmeHenbCb",
                  ha_s1mme_henb_cb__get_packed_size,
                  ha_s1mme_henb_cb__pack,
                  ha_s1mme_henb_cb__unpack,
                  ha_s1mme_henb_cb__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,S1MME_X2_HENB)];
    SET_META_INFO(entry,
                  "HaS1mmeX2Henb",
                  ha_s1mme_x2_henb__get_packed_size,
                  ha_s1mme_x2_henb__pack,
                  ha_s1mme_x2_henb__unpack,
                  ha_s1mme_x2_henb__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,S1MME_X2_ENB)];
    SET_META_INFO(entry,
                  "HaS1mmeX2Enb",
                  ha_s1mme_x2_enb__get_packed_size,
                  ha_s1mme_x2_enb__pack,
                  ha_s1mme_x2_enb__unpack,
                  ha_s1mme_x2_enb__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,S1MME_X2_SERVED_CELL)];
    SET_META_INFO(entry,
                  "HaS1mmeX2ServedCell",
                  ha_s1mme_x2_served_cell__get_packed_size,
                  ha_s1mme_x2_served_cell__pack,
                  ha_s1mme_x2_served_cell__unpack,
                  ha_s1mme_x2_served_cell__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,S1MME_SCTP_RED_GLB_DATA)];
    SET_META_INFO(entry,
                  "HaS1mmeSctpRedGlbData",
                  ha_s1mme_sctp_red_glb_data__get_packed_size,
                  ha_s1mme_sctp_red_glb_data__pack,
                  ha_s1mme_sctp_red_glb_data__unpack,
                  ha_s1mme_sctp_red_glb_data__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,S1MME_SCTP_RED_GLB_EP)];
    SET_META_INFO(entry,
                  "HaS1mmeSctpRedGlbEp",
                  ha_s1mme_sctp_red_glb_ep__get_packed_size,
                  ha_s1mme_sctp_red_glb_ep__pack,
                  ha_s1mme_sctp_red_glb_ep__unpack,
                  ha_s1mme_sctp_red_glb_ep__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,S1MME_SCTP_RED_GLB_PMTU)];
    SET_META_INFO(entry,
                  "HaS1mmeSctpRedGlbPmtu",
                  ha_s1mme_sctp_red_glb_pmtu__get_packed_size,
                  ha_s1mme_sctp_red_glb_pmtu__pack,
                  ha_s1mme_sctp_red_glb_pmtu__unpack,
                  ha_s1mme_sctp_red_glb_pmtu__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,S1MME_SCTP_RED_EP_DATA)];
    SET_META_INFO(entry,
                  "HaS1mmeSctpRedEpData",
                  ha_s1mme_sctp_red_ep_data__get_packed_size,
                  ha_s1mme_sctp_red_ep_data__pack,
                  ha_s1mme_sctp_red_ep_data__unpack,
                  ha_s1mme_sctp_red_ep_data__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,S1MME_SCTP_RED_EP_ASSOCOBJ)];
    SET_META_INFO(entry,
                  "HaS1mmeSctpRedEpAssocobj",
                  ha_s1mme_sctp_red_ep_assocobj__get_packed_size,
                  ha_s1mme_sctp_red_ep_assocobj__pack,
                  ha_s1mme_sctp_red_ep_assocobj__unpack,
                  ha_s1mme_sctp_red_ep_assocobj__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,HENBM_INST_CFG)];
    SET_META_INFO(entry,
                  "HaHenbmInstCfg",
                  ha_henbm_inst_cfg__get_packed_size,
                  ha_henbm_inst_cfg__pack,
                  ha_henbm_inst_cfg__unpack,
                  ha_henbm_inst_cfg__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,HENB_DATA_CB)];
    SET_META_INFO(entry,
                  "HaHenbDataCb",
                  ha_henb_data_cb__get_packed_size,
                  ha_henb_data_cb__pack,
                  ha_henb_data_cb__unpack,
                  ha_henb_data_cb__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,HENB_DATA_CSG)];
    SET_META_INFO(entry,
                  "HaHenbDataCsg",
                  ha_henb_data_csg__get_packed_size,
                  ha_henb_data_csg__pack,
                  ha_henb_data_csg__unpack,
                  ha_henb_data_csg__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,HENB_DATA_TAI)];
    SET_META_INFO(entry,
                  "HaHenbDataTai",
                  ha_henb_data_tai__get_packed_size,
                  ha_henb_data_tai__pack,
                  ha_henb_data_tai__unpack,
                  ha_henb_data_tai__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,UE_DATA_CB)];
    SET_META_INFO(entry,
                  "HaUeDataCb",
                  ha_ue_data_cb__get_packed_size,
                  ha_ue_data_cb__pack,
                  ha_ue_data_cb__unpack,
                  ha_ue_data_cb__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,TE_DATA_CB)];
    SET_META_INFO(entry,
                  "HaTeDataCb",
                  ha_te_data_cb__get_packed_size,
                  ha_te_data_cb__pack,
                  ha_te_data_cb__unpack,
                  ha_te_data_cb__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,GTPU_STAT)];
    SET_META_INFO(entry,
                  "HaGtpuStat",
                  ha_gtpu_stat__get_packed_size,
                  ha_gtpu_stat__pack,
                  ha_gtpu_stat__unpack,
                  ha_gtpu_stat__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,X2_HENB_DATA_CB)];
    SET_META_INFO(entry,
                  "HaX2HenbDataCb",
                  ha_x2_henb_data_cb__get_packed_size,
                  ha_x2_henb_data_cb__pack,
                  ha_x2_henb_data_cb__unpack,
                  ha_x2_henb_data_cb__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,HENB_SCTP_RED_GLB_DATA)];
    SET_META_INFO(entry,
                  "HaHenbSctpRedGlbData",
                  ha_henb_sctp_red_glb_data__get_packed_size,
                  ha_henb_sctp_red_glb_data__pack,
                  ha_henb_sctp_red_glb_data__unpack,
                  ha_henb_sctp_red_glb_data__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,HENB_SCTP_RED_GLB_EP)];
    SET_META_INFO(entry,
                  "HaHenbSctpRedGlbEp",
                  ha_henb_sctp_red_glb_ep__get_packed_size,
                  ha_henb_sctp_red_glb_ep__pack,
                  ha_henb_sctp_red_glb_ep__unpack,
                  ha_henb_sctp_red_glb_ep__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,HENB_SCTP_RED_GLB_PMTU)];
    SET_META_INFO(entry,
                  "HaHenbSctpRedGlbPmtu",
                  ha_henb_sctp_red_glb_pmtu__get_packed_size,
                  ha_henb_sctp_red_glb_pmtu__pack,
                  ha_henb_sctp_red_glb_pmtu__unpack,
                  ha_henb_sctp_red_glb_pmtu__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,HENB_SCTP_RED_EP_DATA)];
    SET_META_INFO(entry,
                  "HaHenbSctpRedEpData",
                  ha_henb_sctp_red_ep_data__get_packed_size,
                  ha_henb_sctp_red_ep_data__pack,
                  ha_henb_sctp_red_ep_data__unpack,
                  ha_henb_sctp_red_ep_data__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,HENB_SCTP_RED_EP_ASSOCOBJ)];
    SET_META_INFO(entry,
                  "HaHenbSctpRedEpAssocobj",
                  ha_henb_sctp_red_ep_assocobj__get_packed_size,
                  ha_henb_sctp_red_ep_assocobj__pack,
                  ha_henb_sctp_red_ep_assocobj__unpack,
                  ha_henb_sctp_red_ep_assocobj__free_unpacked);
    entry = &record_meta_table[RECORDID(HA,CH_ROW_MSG)];
    SET_META_INFO(entry,
                  "HaChRowMsg",
                  ha_ch_row_msg__get_packed_size,
                  ha_ch_row_msg__pack,
                  ha_ch_row_msg__unpack,
                  ha_ch_row_msg__free_unpacked);
}
