/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: record_alarm.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "record_alarm.pb-c.h"
void   alarm_index__init
                     (AlarmIndex         *message)
{
  static AlarmIndex init_value = ALARM_INDEX__INIT;
  *message = init_value;
}
size_t alarm_index__get_packed_size
                     (const AlarmIndex *message)
{
  assert(message->base.descriptor == &alarm_index__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alarm_index__pack
                     (const AlarmIndex *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &alarm_index__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alarm_index__pack_to_buffer
                     (const AlarmIndex *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &alarm_index__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AlarmIndex *
       alarm_index__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AlarmIndex *)
     protobuf_c_message_unpack (&alarm_index__descriptor,
                                allocator, len, data);
}
void   alarm_index__free_unpacked
                     (AlarmIndex *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &alarm_index__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alarm_level__init
                     (AlarmLevel         *message)
{
  static AlarmLevel init_value = ALARM_LEVEL__INIT;
  *message = init_value;
}
size_t alarm_level__get_packed_size
                     (const AlarmLevel *message)
{
  assert(message->base.descriptor == &alarm_level__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alarm_level__pack
                     (const AlarmLevel *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &alarm_level__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alarm_level__pack_to_buffer
                     (const AlarmLevel *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &alarm_level__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AlarmLevel *
       alarm_level__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AlarmLevel *)
     protobuf_c_message_unpack (&alarm_level__descriptor,
                                allocator, len, data);
}
void   alarm_level__free_unpacked
                     (AlarmLevel *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &alarm_level__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   alarm_text__init
                     (AlarmText         *message)
{
  static AlarmText init_value = ALARM_TEXT__INIT;
  *message = init_value;
}
size_t alarm_text__get_packed_size
                     (const AlarmText *message)
{
  assert(message->base.descriptor == &alarm_text__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alarm_text__pack
                     (const AlarmText *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &alarm_text__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alarm_text__pack_to_buffer
                     (const AlarmText *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &alarm_text__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AlarmText *
       alarm_text__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AlarmText *)
     protobuf_c_message_unpack (&alarm_text__descriptor,
                                allocator, len, data);
}
void   alarm_text__free_unpacked
                     (AlarmText *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &alarm_text__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor alarm_index__field_descriptors[1] =
{
  {
    "alarm_index",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AlarmIndex, alarm_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned alarm_index__field_indices_by_name[] = {
  0,   /* field[0] = alarm_index */
};
static const ProtobufCIntRange alarm_index__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor alarm_index__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AlarmIndex",
  "AlarmIndex",
  "AlarmIndex",
  "",
  sizeof(AlarmIndex),
  1,
  alarm_index__field_descriptors,
  alarm_index__field_indices_by_name,
  1,  alarm_index__number_ranges,
  (ProtobufCMessageInit) alarm_index__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alarm_level__field_descriptors[1] =
{
  {
    "alarm_level",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AlarmLevel, alarm_level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned alarm_level__field_indices_by_name[] = {
  0,   /* field[0] = alarm_level */
};
static const ProtobufCIntRange alarm_level__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor alarm_level__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AlarmLevel",
  "AlarmLevel",
  "AlarmLevel",
  "",
  sizeof(AlarmLevel),
  1,
  alarm_level__field_descriptors,
  alarm_level__field_indices_by_name,
  1,  alarm_level__number_ranges,
  (ProtobufCMessageInit) alarm_level__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor alarm_text__field_descriptors[2] =
{
  {
    "alarm_text",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AlarmText, alarm_text),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log_module",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(AlarmText, has_log_module),
    offsetof(AlarmText, log_module),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned alarm_text__field_indices_by_name[] = {
  0,   /* field[0] = alarm_text */
  1,   /* field[1] = log_module */
};
static const ProtobufCIntRange alarm_text__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor alarm_text__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AlarmText",
  "AlarmText",
  "AlarmText",
  "",
  sizeof(AlarmText),
  2,
  alarm_text__field_descriptors,
  alarm_text__field_indices_by_name,
  1,  alarm_text__number_ranges,
  (ProtobufCMessageInit) alarm_text__init,
  NULL,NULL,NULL    /* reserved[123] */
};
